{% set name = "canopen" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/canopen-{{ version }}.tar.gz
  sha256: 792084a93c138d5b2a406ddd2d4eb5ce208f03bd8fda60f81ad2bb8d56c6b827

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.6
    - python-can >=3.0.0

test:
  imports:
    - canopen
  commands:
    - pip check
  requires:
    - pip
    - msgpack-python

about:
  home: https://github.com/christiansandberg/canopen
  summary: CANopen stack implementation
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
